# Generated by Django 6.1.1 on 2026-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("pickup_address", models.CharField(blank=True, max_length=255)),
                ("pickup_phone", models.CharField(blank=True, max_length=32)),
                (
                    "working_hours",
                    models.CharField(default="Пн-Нд: Цілодобово", max_length=64),
                ),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
                "ordering": ["order", "name"],
            },
        ),
    ]
